#ifndef INCLUDED_GAMEENGINE_RESOURCEID_H
#define INCLUDED_GAMEENGINE_RESOURCEID_H


namespace GameEngine
{
	enum GlobalResourceTextureID
	{
		GLOBAL_RESOURCE_TEXTURE_ID_PLAYER_SHOT_GREEN_MAIN		= 50,	// 緑モードメイン
		GLOBAL_RESOURCE_TEXTURE_ID_BAR							= 51,	// バー
		GLOBAL_RESOURCE_TEXTURE_ID_CONS_RED_SYMBOL				= 52,	// 赤モードシンボル
		GLOBAL_RESOURCE_TEXTURE_ID_CONS_GREEN_SYMBOL			= 53,	// 緑モードシンボル
		GLOBAL_RESOURCE_TEXTURE_ID_CONS_BLUE_SYMBOL				= 54,	// 青モードシンボル
		GLOBAL_RESOURCE_TEXTURE_ID_PLAYER_SHOT_BLUE_MAIN		= 55,	// 青モードメインショット
		GLOBAL_RESOURCE_TEXTURE_ID_PLAYER_SHOT_RED_MAIN			= 56,	// 赤モードメインショット
	};

	enum GlobalResourceSEID
	{
		GLOBAL_RESOURCE_SE_ID_PLAYER_CHANGE_MODE		= 4,		// モードチェンジ時
	};
}

#endif