#ifndef INCLUDED_GAMEENGINE_RESOURCEID_H
#define INCLUDED_GAMEENGINE_RESOURCEID_H


namespace GameEngine
{
	enum GlobalResourceTextureID
	{
		GLOBAL_RESOURCE_TEXTURE_ID_PLAYER_SHOT_GREEN_MAIN		= 50,	// 緑モードメイン
		GLOBAL_RESOURCE_TEXTURE_ID_BAR							= 51,	// バー
		GLOBAL_RESOURCE_TEXTURE_ID_CONS_RED_SYMBOL				= 52,	// 赤モードシンボル
		GLOBAL_RESOURCE_TEXTURE_ID_CONS_GREEN_SYMBOL			= 53,	// 緑モードシンボル
		GLOBAL_RESOURCE_TEXTURE_ID_CONS_BLUE_SYMBOL				= 54,	// 青モードシンボル
		GLOBAL_RESOURCE_TEXTURE_ID_PLAYER_SHOT_BLUE_MAIN		= 55,	// 青モードメインショット
		GLOBAL_RESOURCE_TEXTURE_ID_PLAYER_SHOT_RED_MAIN			= 56,	// 赤モードメインショット

		GLOBAL_RESOURCE_TEXTURE_ID_MENU_GAME_START				= 58,	// メニュー（ゲームスタート）
		GLOBAL_RESOURCE_TEXTURE_ID_MENU_GAME_START_SELECTED		= 57,	// 選択されたメニュー（ゲームスタート）
		GLOBAL_RESOURCE_TEXTURE_ID_MENU_EXIT					= 59,	// メニュー（終了）
		GLOBAL_RESOURCE_TEXTURE_ID_MENU_EXIT_SELECTED			= 60,	// 選択されたメニュー（終了）
		GLOBAL_RESOURCE_TEXTURE_ID_MENU_SCORE					= 61,	// メニュー（スコア）
		GLOBAL_RESOURCE_TEXTURE_ID_MENU_SCORE_SELECTED			= 62,	// 選択されたメニュー（スコア）
		GLOBAL_RESOURCE_TEXTURE_ID_MENU_REPLAY					= 63,	// メニュー（リプレイ）
		GLOBAL_RESOURCE_TEXTURE_ID_MENU_REPLAY_SELECTED			= 64,	// 選択されたメニュー（リプレイ）
		GLOBAL_RESOURCE_TEXTURE_ID_MENU_CONFIG					= 65,	// メニュー（設定）
		GLOBAL_RESOURCE_TEXTURE_ID_MENU_CONFIG_SELECTED			= 66,	// 選択されたメニュー（設定）

		GLOBAL_RESOURCE_TEXTURE_ID_HI_SCORE						= 67,	// ハイスコア
		GLOBAL_RESOURCE_TEXTURE_ID_GAME_SCORE					= 68,	// スコア
		GLOBAL_RESOURCE_TEXTURE_ID_GAME_KILLED					= 69,	// 撃破数
		GLOBAL_RESOURCE_TEXTURE_ID_GAME_CRYSTAL					= 70,	// クリスタル数
		GLOBAL_RESOURCE_TEXTURE_ID_GAME_POWER					= 71,	// パワー
		GLOBAL_RESOURCE_TEXTURE_ID_GAME_HP						= 72,	// HP
		GLOBAL_RESOURCE_TEXTURE_ID_LOADING_1					= 73,	// ローディング時の画像
		GLOBAL_RESOURCE_TEXTURE_ID_LOADING_2					= 74,	// ローディング時の画像
		GLOBAL_RESOURCE_TEXTURE_ID_INITIALIZE					= 75,	// 初期化状態時の画像
	};

	enum GlobalResourceSEID
	{
		GLOBAL_RESOURCE_SE_ID_PLAYER_CHANGE_MODE		= 4,		// モードチェンジ時
		GLOBAL_RESOURCE_SE_ID_PLAYER_DAMAGED			= 5,		// プレイヤーダメージ時
		GLOBAL_RESOURCE_SE_ID_PLAYER_DESTROYED			= 6,		// プレイヤー破壊時
		GLOBAL_RESOURCE_SE_ID_MENU_SELECTED				= 7,		// メニュー選択時
	};
}

#endif