#ifndef INCLUDED_GAMEENGINE_RESOURCEID_H
#define INCLUDED_GAMEENGINE_RESOURCEID_H


namespace GameEngine
{
	enum GlobalResourceTextureID
	{
		GLOBAL_RESOURCE_TEXTURE_ID_PLAYER_SHOT_GREEN_MAIN		= 50,	// 緑モードメイン
		GLOBAL_RESOURCE_TEXTURE_ID_BAR							= 51,	// バー
		GLOBAL_RESOURCE_TEXTURE_ID_CONS_RED_SYMBOL				= 52,	// 赤モードシンボル
		GLOBAL_RESOURCE_TEXTURE_ID_CONS_GREEN_SYMBOL			= 53,	// 緑モードシンボル
		GLOBAL_RESOURCE_TEXTURE_ID_CONS_BLUE_SYMBOL				= 54,	// 青モードシンボル
		GLOBAL_RESOURCE_TEXTURE_ID_PLAYER_SHOT_BLUE_MAIN		= 55,	// 青モードメインショット
		GLOBAL_RESOURCE_TEXTURE_ID_PLAYER_SHOT_RED_MAIN			= 56,	// 赤モードメインショット

		GLOBAL_RESOURCE_TEXTURE_ID_MENU_GAME_START				= 58,	// メニュー（ゲームスタート）
		GLOBAL_RESOURCE_TEXTURE_ID_MENU_GAME_START_SELECTED		= 57,	// 選択されたメニュー（ゲームスタート）
		GLOBAL_RESOURCE_TEXTURE_ID_MENU_EXIT					= 59,	// メニュー（終了）
		GLOBAL_RESOURCE_TEXTURE_ID_MENU_EXIT_SELECTED			= 60,	// 選択されたメニュー（終了）
		GLOBAL_RESOURCE_TEXTURE_ID_MENU_SCORE					= 61,	// メニュー（スコア）
		GLOBAL_RESOURCE_TEXTURE_ID_MENU_SCORE_SELECTED			= 62,	// 選択されたメニュー（スコア）
		GLOBAL_RESOURCE_TEXTURE_ID_MENU_REPLAY					= 63,	// メニュー（リプレイ）
		GLOBAL_RESOURCE_TEXTURE_ID_MENU_REPLAY_SELECTED			= 64,	// 選択されたメニュー（リプレイ）
		GLOBAL_RESOURCE_TEXTURE_ID_MENU_CONFIG					= 65,	// メニュー（設定）
		GLOBAL_RESOURCE_TEXTURE_ID_MENU_CONFIG_SELECTED			= 66,	// 選択されたメニュー（設定）

		GLOBAL_RESOURCE_TEXTURE_ID_HI_SCORE						= 67,	// ハイスコア
		GLOBAL_RESOURCE_TEXTURE_ID_GAME_SCORE					= 68,	// スコア
		GLOBAL_RESOURCE_TEXTURE_ID_GAME_KILLED					= 69,	// 撃破数
		GLOBAL_RESOURCE_TEXTURE_ID_GAME_CRYSTAL					= 70,	// クリスタル数
		GLOBAL_RESOURCE_TEXTURE_ID_GAME_POWER					= 71,	// パワー
		GLOBAL_RESOURCE_TEXTURE_ID_GAME_HP						= 72,	// HP
		GLOBAL_RESOURCE_TEXTURE_ID_LOADING_1					= 73,	// ローディング時の画像
		GLOBAL_RESOURCE_TEXTURE_ID_LOADING_2					= 74,	// ローディング時の画像
		GLOBAL_RESOURCE_TEXTURE_ID_INITIALIZE					= 75,	// 初期化状態時の画像

		GLOBAL_RESOURCE_TEXTURE_ID_ITEM_CONS_LEVEL_RECOVER_1	= 76,	// 意識ゲージ回復（1）
		GLOBAL_RESOURCE_TEXTURE_ID_ITEM_CONS_LEVEL_RECOVER_2	= 77,	// 意識ゲージ回復（2）
		GLOBAL_RESOURCE_TEXTURE_ID_ITEM_CONS_LEVEL_RECOVER_3	= 78,	// 意識ゲージ回復（3）
		GLOBAL_RESOURCE_TEXTURE_ID_ITEM_CONS_LEVEL_RECOVER_4	= 79,	// 意識ゲージ回復（4）
		GLOBAL_RESOURCE_TEXTURE_ID_ITEM_CONS_LEVEL_RECOVER_5	= 80,	// 意識ゲージ回復（5）
		GLOBAL_RESOURCE_TEXTURE_ID_ITEM_RECOVER_1				= 81,	// HP回復(1)
		GLOBAL_RESOURCE_TEXTURE_ID_ITEM_RECOVER_2				= 82,	// HP回復(2)
		GLOBAL_RESOURCE_TEXTURE_ID_EFFECT_CONS_SKILL_1			= 83,	// 意識技エフェクト(1)
		GLOBAL_RESOURCE_TEXTURE_ID_EFFECT_CONS_SKILL_2			= 84,	// 意識技エフェクト(2)
		GLOBAL_RESOURCE_TEXTURE_ID_EFFECT_CONS_SKILL_3			= 85,	// 意識技エフェクト(3)
		GLOBAL_RESOURCE_TEXTURE_ID_STAGE_BACKGROUND				= 86,	// ステージ背景
		GLOBAL_RESOURCE_TEXTURE_ID_STAGE_BACKGROUND_2			= 87,	// ステージ背景(2)
		GLOBAL_RESOURCE_TEXTURE_ID_TITLE						= 88,	// タイトル
		GLOBAL_RESOURCE_TEXTURE_ID_TITLE_2						= 89,	// タイトル(2)
		GLOBAL_RESOURCE_TEXTURE_ID_GENERAL_BACKGROUND			= 90,	// ゲーム一般背景
		GLOBAL_RESOURCE_TEXTURE_ID_DIFFICULTY_SELECTION_CALM	= 91,	// 難易度CALM選択
		GLOBAL_RESOURCE_TEXTURE_ID_DIFFICULTY_SELECTION_EASY	= 92,	// 難易度EASY選択
		GLOBAL_RESOURCE_TEXTURE_ID_DIFFICULTY_SELECTION_NORMAL	= 93,	// 難易度NORMAL選択
		GLOBAL_RESOURCE_TEXTURE_ID_DIFFICULTY_SELECTION_HARD	= 94,	// 難易度HARD選択
		GLOBAL_RESOURCE_TEXTURE_ID_DIFFICULTY_SELECTION_HAZARD	= 95,	// 難易度HAZARD選択
		GLOBAL_RESOURCE_TEXTURE_ID_DIFFICULTY_SELECTION_TITLE	= 96,	// 難易度選択画面のタイトル画像
		GLOBAL_RESOURCE_TEXTURE_ID_STAGE_SELECTION_STAGE_1		= 97,	// Stage 1 選択
		GLOBAL_RESOURCE_TEXTURE_ID_STAGE_SELECTION_STAGE_2		= 98,	// Stage 2 選択
		GLOBAL_RESOURCE_TEXTURE_ID_STAGE_SELECTION_STAGE_3		= 99,	// Stage 3 選択
		GLOBAL_RESOURCE_TEXTURE_ID_STAGE_SELECTION_STAGE_4		= 100,	// Stage 4 選択
		GLOBAL_RESOURCE_TEXTURE_ID_STAGE_SELECTION_STAGE_5		= 101,	// Stage 5 選択
		GLOBAL_RESOURCE_TEXTURE_ID_STAGE_SELECTION_TITLE		= 102,	// ステージ選択画面のタイトル画像
		GLOBAL_RESOURCE_TEXTURE_ID_SCORE_CALM					= 103,	// スコア画面CALM
		GLOBAL_RESOURCE_TEXTURE_ID_SCORE_EASY					= 104,	// スコア画面EASY
		GLOBAL_RESOURCE_TEXTURE_ID_SCORE_NORMAL					= 105,	// スコア画面NORMAL
		GLOBAL_RESOURCE_TEXTURE_ID_SCORE_HARD					= 106,	// スコア画面HARD
		GLOBAL_RESOURCE_TEXTURE_ID_SCORE_HAZARD					= 107,	// スコア画面HAZARD
		GLOBAL_RESOURCE_TEXTURE_ID_SCORE_TITLE					= 108,	// スコア画面タイトル画像
		GLOBAL_RESOURCE_TEXTURE_ID_REPLAY_TITLE					= 109,	// リプレイ画面タイトル画像
		GLOBAL_RESOURCE_TEXTURE_ID_REPLAY_ENTRY_TITLE			= 110,	// リプレイエントリ画面タイトル画像
	};

	enum GlobalResourceSEID
	{
		GLOBAL_RESOURCE_SE_ID_PLAYER_CHANGE_MODE		= 4,		// モードチェンジ時
		GLOBAL_RESOURCE_SE_ID_PLAYER_DAMAGED			= 5,		// プレイヤーダメージ時
		GLOBAL_RESOURCE_SE_ID_PLAYER_DESTROYED			= 6,		// プレイヤー破壊時
		GLOBAL_RESOURCE_SE_ID_MENU_SELECTED				= 7,		// メニュー選択時
		GLOBAL_RESOURCE_SE_ID_EFFECT_CONS_SKILL_1		= 8,		// 意識技エフェクト(1)
		GLOBAL_RESOURCE_SE_ID_EFFECT_CONS_SKILL_2		= 9,		// 意識技エフェクト(2)
		GLOBAL_RESOURCE_SE_ID_EFFECT_CONS_SKILL_3		= 10,		// 意識技エフェクト(3)
		GLOBAL_RESOURCE_SE_ID_EFFECT_CONS_SKILL_4		= 11,		// 意識技エフェクト(4)
	};

	enum GlobalResourceBGMID
	{
		GLOBAL_RESOURCE_BGM_ID_MENU						= 0,		// メニュー画面
	};

	enum GlobalResourceModelID
	{
		GLOBAL_RESOURCE_MODEL_ID_PLAYER					= 0,		// プレイヤー
	};
}

#endif